os:
  - linux
  - osx

sudo: false

language: csharp
solution: ./ATPR/ATPR.sln

install:
  - nuget restore ./ATPR/ATPR.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ./ATPR/ATPR.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ATPR/ATPR.Tests/bin/Release/ATPR.Tests.dll

notifications:
  on_success: never
  on_failure: always

